[pxc]
pxc-node1 ansible_host=192.168.122.31 ansible_user=ubuntu
pxc-node2 ansible_host=192.168.122.32 ansible_user=ubuntu
pxc-node3 ansible_host=192.168.122.33 ansible_user=ubuntu

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
